function E_tau_tau=direct_compute_cable_strain_E_tau_tau(R,omega,theta,s,u0_k,v0_k,u_k,v_k)
alpha=(2*pi*R*omega)/sqrt(1+(2*pi*R*omega)^2);
beta=sqrt(1-alpha^2);
x_k=[R*cos(2*pi*omega*s-theta),R*sin(2*pi*omega*s-theta),s];
J=get_jacobain_J(x_k,u0_k);
on_x_F_i3=get_green_deform_grad_thirdcomp_on_x_F_i3(x_k,u_k,v_k,J);
E_tau_tau_t=0.5*alpha^2+(R*u0_k(3)*alpha*beta/J)*(cos(2*pi*omega*s-theta)^2-sin(2*pi*omega*s-theta)^2)+...
    (R*u0_k(3)*beta/J)^2*(1-2*cos(2*pi*omega*s-theta)*sin(2*pi*omega*s-theta))...
    +on_x_F_i3(1)*(-alpha*sin(2*pi*omega*s-theta)+(R*u0_k(3)*beta/J)*(sin(2*pi*omega*s-theta)))...
    +on_x_F_i3(2)*(alpha*cos(2*pi*omega*s-theta)+(R*u0_k(3)*beta/J)*(-cos(2*pi*omega*s-theta)))...
    +0.5*(on_x_F_i3(1)^2+on_x_F_i3(2)^2+on_x_F_i3(3)^2)*beta^2-0.5;
on_x_F_i3_0=get_green_deform_grad_thirdcomp_on_x_F_i3(x_k,u0_k,v0_k,J);
E_tau_tau_0=0.5*alpha^2+(R*u0_k(3)*alpha*beta/J)*(cos(2*pi*omega*s-theta)^2-sin(2*pi*omega*s-theta)^2)+...
    (R*u0_k(3)*beta/J)^2*(1-2*cos(2*pi*omega*s-theta)*sin(2*pi*omega*s-theta))...
    +on_x_F_i3_0(1)*(-alpha*sin(2*pi*omega*s-theta)+(R*u0_k(3)*beta/J)*(sin(2*pi*omega*s-theta)))...
    +on_x_F_i3_0(2)*(alpha*cos(2*pi*omega*s-theta)+(R*u0_k(3)*beta/J)*(-cos(2*pi*omega*s-theta)))...
    +0.5*(on_x_F_i3_0(1)^2+on_x_F_i3_0(2)^2+on_x_F_i3_0(3)^2)*beta^2-0.5;
E_tau_tau=E_tau_tau_t-E_tau_tau_0;
%%linear

 % E_tau_tau=(-alpha*x_k(2)/R)*v_k(1)+(alpha*x_k(1)/R)*v_k(2)+beta^2*(v_k(3)-1)+beta^2*x_k(2)*u_k(1)+(-beta^2*x_k(1))*u_k(2)+alpha*R*u_k(3);

