function [A_pq,B_pq_l,u_k,v_k,Cu_k,Cv_k]=nonlin_rod_assymbling_matrixs_arbitrary(R_cables,omega_cables,theta_cables,n_cables,s,u0_k,v0_k,epsilon_p_cables,measure_error_level,spatial_resolution)
% disp("now on location s=")
% disp(s)
[u_k,v_k]=nonlinear_least_square_solve_darboux_arbitrary(R_cables,omega_cables,theta_cables,n_cables,s,u0_k,v0_k,epsilon_p_cables);
[Cu_k,Cv_k]=nonlinear_get_error_matrix_arbitrary(R_cables,omega_cables,theta_cables,n_cables,s,u0_k,v0_k,u_k,v_k,measure_error_level,spatial_resolution);
Imat=eye(3);
Zmat=zeros(3,3);
A_pq=[Zmat,Imat*v_k(1),Imat*v_k(2),Imat*v_k(3);...
    Zmat,Zmat,Imat*u_k(3),-Imat*u_k(2);...
    Zmat,-Imat*u_k(3),Zmat,Imat*u_k(1);...
    Zmat,Imat*u_k(2),-Imat*u_k(1),Zmat];
B_pq_l=zeros(n_cables,12,12);
for l=1:n_cables
    B_pq_l(l,:,:)=...
    [Zmat,Imat*Cv_k(1,l),Imat*Cv_k(2,l),Imat*Cv_k(3,l);...
    Zmat,Zmat,Imat*Cu_k(3,l),-Imat*Cu_k(2,l);...
    Zmat,-Imat*Cu_k(3,l),Zmat,Imat*Cu_k(1,l);...
    Zmat,Imat*Cu_k(2,l),-Imat*Cu_k(1,l),Zmat];
end
% B_pq_l=B_pq_l*measure_error_level*sqrt(spatial_resolution);
